### ISSUE TITLE
no moudle named torch

### ISSUE THREAD

**Issue by lifeiXiao** [PKU-EPIC/GraspNeRF#19]
whatever GPU or pytorch i use,it
![image](https://github.com/PKU-EPIC/GraspNeRF/assets/79552815/6ff0741b-c812-4890-ba50-f5b258b52003)

**Comment by lifeiXiao** [comment]
we need add package by hand to pythonpath

**Comment by LZzzin1** [comment]
how to？

**Comment by LZzzin1** [comment]
any sample code?

**Comment by huamo555** [comment]
> 将包添加到 pythonpath

您好，请问您解决这个问题了吗？是怎么样手动添加呢？

**Comment by huamo555** [comment]
我遇到了相同的问题，无法解决。请问有具体的解决方案吗？
