### ISSUE TITLE
Torch error during training and testing 

### ISSUE THREAD

**Issue by camilletaglione** [PKU-EPIC/GraspNeRF#23]
Hello, 
A really impressive contribution.
I am running the code on an RTX A4000 
I use Torch 2.1 with cuda 12.1
after launching both 
```
bash run_simgrasp.sh
```
or 
```
bash train.sh GPU_ID
```
I get the following error

>File "/home/user/miniconda3/envs/GRASP/lib/python3.9/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
>ImportError: /home/user/miniconda3/envs/GRASP/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: cblas_gemm_bf16bf16f32

Do you have an idea, what can I do to fix that ?
Thanks in advance

**Comment by DeepDuke** [comment]
same problem...
