### ISSUE TITLE
Franka Emika Panda

### ISSUE THREAD

**Issue by junsukha** [PKU-EPIC/GraspNeRF#3]
Hi!
Thank you for the work you've done!

I was wondering if you will be adding any instructions about how to use your code with Panda?
I'm doing a project using a Panda arm robot and I'm a newbie on working with a robot. 
I suppose you used ROS for the experiment?

Thanks!

**Comment by Daiqy** [comment]
Hi! For instructions on how to use the code with Panda, please refer to [VGN](https://github.com/ethz-asl/vgn). And we do use ROS in our real robot experiments.

**Comment by junsukha** [comment]
Thank you!!
