### ISSUE TITLE
Simulating grasp using pybullet and blender

### ISSUE THREAD

**Issue by vincent341** [PKU-EPIC/GraspNeRF#5]
Hi. Thanks for your wonderful work and sharing the code. It benefits me a lot. It would be highly appreciated if you could provide more information about simulating grasp using pybullet and blender. How to use your scripts to generate simulation scenes and grasps? Appreciate your help!

**Comment by Daiqy** [comment]
Hi! We directly use the grasp labels and scene layout from [GIGA](https://github.com/UT-Austin-RPL/GIGA). Please refer to this project for details about scene generation and grasp simulation.

**Comment by vincent341** [comment]
> Hi! We directly use the grasp labels and scene layout from [GIGA](https://github.com/UT-Austin-RPL/GIGA). Please refer to this project for details about scene generation and grasp simulation.

Thanks so much for your quick reply! I noticed that **blender** is used for rendering glare and transparent objects. Would you mind sharing the code which rendering the glare and transparent scenes? I didn't find it in the repo. It would be very helpful to me. Appreciate it very much!

**Comment by Daiqy** [comment]
Sure. We will release the data generator code this or next week.
