### ISSUE TITLE
Grasping TSDF on custom images

### ISSUE THREAD

**Issue by Hari-0505** [PKU-EPIC/GraspNeRF#7]
Hi,

Thanks for sharing your wonderful work!
I'm looking to generate TSDF and grasp samples for custom images!

Could you point me to the relevant script!
Thanks

**Comment by Daiqy** [comment]
Hi! Please follow the implementation from [VGN](https://github.com/ethz-asl/vgn) and [GIGA](https://github.com/UT-Austin-RPL/GIGA).
